name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t backend-image ./backend

      - name: Build frontend image
        run: docker build -t frontend-image ./frontend

      - name: Push Docker images
        run: |
          docker tag backend-image ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
          docker tag frontend-image ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/fusionpact-devops-challenge-solution
            docker compose down
            docker compose up -d
